import type { SandboxPatient } from './types.js';

export const sandboxPatients: SandboxPatient[] = [
  {
    name: 'Elvira Valadez-Nucleus',
    tier: 'GOLD',
    demographics: {
      given_name: 'Elvira',
      family_name: 'Valadez-Nucleus',
      gender: 'FEMALE',
      date_of_birth: '1970-12-26',
      address_lines: ['703 Ankunding Trail Unit 45'],
      address_city: 'Boston',
      address_state: 'MA',
      postal_code: '02215',
      patient_id: 'test-001',
    },
  },
  {
    name: 'Glynda Sugarman-Nucleus',
    tier: 'GOLD',
    demographics: {
      given_name: 'Glynda',
      family_name: 'Sugarman-Nucleus',
      gender: 'FEMALE',
      date_of_birth: '1968-01-01',
      address_lines: ['123 Test Street'],
      address_city: 'Anytown',
      address_state: 'NY',
      postal_code: '11222',
      patient_id: 'test-002',
    },
  },
  {
    name: 'Freda Quently-Nucleus',
    tier: 'GOLD',
    demographics: {
      given_name: 'Freda',
      family_name: 'Quently-Nucleus',
      gender: 'FEMALE',
      date_of_birth: '1994-03-22',
      address_lines: ['123 Main Street'],
      address_city: 'Anytown',
      address_state: 'NY',
      postal_code: '11206',
      patient_id: 'test-003',
    },
  },
  {
    name: 'Kam Quark-Nucleus',
    tier: 'GOLD',
    demographics: {
      given_name: 'Kam',
      family_name: 'Quark-Nucleus',
      gender: 'MALE',
      date_of_birth: '1954-12-01',
      address_lines: ['999 Dev Drive'],
      address_city: 'Brooklyn',
      address_state: 'NY',
      postal_code: '11111',
      patient_id: 'test-004',
    },
  },
  {
    name: 'Artie Jointson-Nucleus',
    tier: 'GOLD',
    demographics: {
      given_name: 'Artie',
      family_name: 'Jointson-Nucleus',
      gender: 'MALE',
      date_of_birth: '1951-08-15',
      address_lines: ['123 Art St'],
      address_city: 'Anytown',
      address_state: 'NY',
      postal_code: '11222',
      patient_id: 'test-005',
    },
  },
  {
    name: 'Hart Fallon',
    tier: 'BRONZE',
    demographics: {
      given_name: 'Hart',
      family_name: 'Fallon',
      gender: 'MALE',
      date_of_birth: '1952-10-01',
      address_lines: ['456 Elm Street'],
      address_city: 'Sample City',
      address_state: 'NY',
      postal_code: '11206',
      patient_id: 'test-007',
    },
  },
  {
    name: 'Tuma Nephro',
    tier: 'BRONZE',
    demographics: {
      given_name: 'Tuma',
      family_name: 'Nephro',
      gender: 'FEMALE',
      date_of_birth: '1959-04-05',
      address_lines: ['789 Dev Street'],
      address_city: 'Sample City',
      address_state: 'NY',
      postal_code: '11211',
      patient_id: 'test-012',
    },
  },
  {
    name: 'Grant Bogisich',
    tier: 'BRONZE',
    demographics: {
      given_name: 'Grant',
      family_name: 'Bogisich',
      gender: 'MALE',
      date_of_birth: '1995-09-05',
      address_lines: ['710 Batz Estate'],
      address_city: 'Harwich',
      address_state: 'MA',
      postal_code: '02645',
      patient_id: 'test-008',
    },
  },
];
